repos:
- repo: builtin
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: check-executables-have-shebangs
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.12.21
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.9
  hooks:
    - id: ruff-check
      args: ["--fix"]
    - id: ruff-format
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.49.1
  hooks:
    - id: markdownlint
      args: ["--config", ".markdownlint.jsonc"]
- repo: local
  hooks:
    - id: prettier
      name: prettier
      entry: npm exec --no -- prettier --write
      language: system
      types_or: [css, javascript]
