volumes:
  rabbitmq_data:
  rabbitmq_logs:
  typesense_data:

services:
  aipscan:
    build: ./
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
      - TYPESENSE_HOST=typesense
      - TYPESENSE_API_KEY=xyz
    ports:
      - 5000:5000
    volumes:
      - "./:/src:rw"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    depends_on:
      - aipscan

  celery-worker:
    build: ./
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
      - TYPESENSE_HOST=typesense
      - TYPESENSE_API_KEY=xyz
    command: celery -A AIPscan.worker.celery worker --loglevel=info
    volumes:
      - "./:/src:rw"
    depends_on:
      - rabbitmq
      - aipscan

  typesense:
    image: typesense/typesense:0.26.0.rc23
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz
    volumes:
      - typesense_data:/data
    ports:
      - 8108:8108
