services:
  aipscan:
    networks:
      - am_default

  rabbitmq:
    networks:
      - am_default

  celery-worker:
    networks:
      - am_default

  aipscan-mysql:
    networks:
      - am_default

networks:
  am_default:
    external: true
