volumes:
  rabbitmq_data:
  rabbitmq_logs:

services:
  aipscan:
    build: ./
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
    ports:
      - 5000:5000
    volumes:
      - "./:/src:rw"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    depends_on:
      - aipscan

  celery-worker:
    build: ./
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
    command: celery worker -A AIPscan.worker.celery --loglevel=info
    volumes:
      - "./:/src:rw"
    depends_on:
      - rabbitmq
      - aipscan
