#!/usr/bin/env python3
import sys

from app import cli

from AIPscan import db, typesense_helpers
from config import CONFIGS


def main():
    # Initialize Flash app context
    app = cli.create_app_instance(CONFIGS[cli.config_name], db)

    with app.app_context():
        print("Initializing index...")
        typesense_helpers.initialize_index()

        print("Populating index...")
        for progress in typesense_helpers.populate_index():
            print(f"{progress[0]}: {progress[1]}/{progress[2]}")


if __name__ == "__main__":
    sys.exit(main())
