#!/usr/bin/env python3
import sys

from app import cli

from AIPscan import db, typesense_helpers
from config import CONFIGS


def main():
    # Initialize Flash app context
    app = cli.create_app_instance(CONFIGS[cli.config_name], db)

    with app.app_context():
        client = typesense_helpers.client()

        results = typesense_helpers.list_collections(client)
        for result in results:
            print(f"Name: {result['name']}")
            print(f"* Fields: {len(result['fields'])}")
            print(f"* Documents: {result['num_documents']}\n")

        print(f"Number of collections: {len(results)}")


if __name__ == "__main__":
    sys.exit(main())
