name: Release

# This workflow is an interim release process that currently only builds and
# publishes container images, but should be expanded into a full release
# pipeline with additional steps such as running automated tests, building and
# packaging artifacts, publishing to PyPI and performing other necessary checks
# to ensure reliable and automated releases.

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version to release (e.g., 1.2.3 or 1.2.3-rc.1)"
        required: true
        type: string

env:
  REGISTRY_IMAGE: artefactual/aipscan

jobs:
  validate-version:
    name: Validate semantic version
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: .github/actions/validate-semver
      - name: Validate semantic version
        uses: ./.github/actions/validate-semver
        with:
          version: ${{ github.event.inputs.version }}

  publish:
    needs: validate-version
    name: Publish Docker image
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            ${{ github.event.inputs.version }}
            latest
      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
